version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NODE_ENV=${NODE_ENV:-development}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - UPLOAD_DIR=/app/uploads
      - EXTERNAL_IMAGES_PATH=/app/public/external-images
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ${NODE_ENV:-development}-uploads:/app/uploads
      - ${NODE_ENV:-development}-cache:/app/.next/cache
      - ${PWD}/external-images:/app/public/external-images:ro
      # Mount source in development for hot reloading
      - ${NODE_ENV:-development}-node_modules:/app/node_modules
      - ${NODE_ENV:-development}-source:/app:delegated
    user: "nextjs"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - aixchange-network
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    volumes:
      - ${NODE_ENV:-development}-postgres:/var/lib/postgresql/data
      - ./backups:/backups
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - aixchange-network
    restart: unless-stopped

  backup:
    image: postgres:14-alpine
    volumes:
      - ./backups:/backups
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGHOST=db
    command: |
      /bin/sh -c '
        while true; do
          DATE=$$(date +%Y%m%d_%H%M%S)
          pg_dump -U $$POSTGRES_USER -d $$POSTGRES_DB -F c -f /backups/backup_$$DATE.dump
          find /backups -type f -mtime +7 -delete
          sleep 86400
        done
      '
    depends_on:
      - db
    networks:
      - aixchange-network
    restart: unless-stopped

networks:
  aixchange-network:
    driver: bridge

volumes:
  development-postgres:
  development-uploads:
  development-cache:
  development-node_modules:
  development-source:
  production-postgres:
  production-uploads:
  production-cache:
  production-node_modules:
  production-source: