name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: azu-oncology-rd-self-hosted-linux

    steps:
      - name: Deploy with Appleboy SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: portal.aixplore.odsp.astrazeneca.net
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "/data" ]; then
              sudo mkdir -p /data
              sudo chown ec2-user:ec2-user /data
            fi
            
            cd /data
            
            sudo rm -rf aixplore
            echo "Cloning fresh repository..."
            sudo git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} aixplore
            sudo chown -R ec2-user:ec2-user aixplore
            
            cd aixplore
            
            if [ ! -f "../.env" ]; then
              echo "Creating .env file..."
              sudo mkdir -p env
              echo "${{ secrets.ENV_FILE }}" | sudo tee ../.env > /dev/null
              sudo chown -R ec2-user:ec2-user env
            fi
            
            cd app/deploy
            chmod +x deploy.sh
            
            ./deploy.sh greenfield --prod
