name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: azu-oncology-rd-self-hosted-linux

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: "ec2-user"
          script: |
            # Navigate to application directory
            cd /data/
            git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            cd ${{ github.repository.name }}

            # Check if .env exists and is valid
            if [ ! -f /data/${{ github.repository.name }}/env/.env ]; then
              echo "Error: .env file not found"
              exit 1
            fi

            # Build and restart containers
            docker compose pull
            docker compose build --no-cache
            docker compose down
            docker compose up -d
