name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: azu-oncology-rd-self-hosted-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug SSH
        run: |
          echo "=== Debug SSH setup ==="
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keygen -l -f ~/.ssh/deploy_key
          echo "=== End Debug ==="

      - name: Deploy
        run: |
          ssh -v -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ec2-user@portal.aixplore.odsp.astrazeneca.net uname
