name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: odsp-aws-small

    steps:
      - name: Test Appleboy SSH Action
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: portal.aixplore.odsp.astrazeneca.net
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            uname -a
